# Package Overview
package_name: bikeshare_model

# Data Files
training_data_file: bike-sharing-dataset.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (Count)
target: cnt

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare__model_output_v

features:      # final features to be use
  - season
  - hr
  - holiday 
  - workingday 
  - weathersit
  - temp  
  - atemp   
  - hum       
  - windspeed
  - year
  - month
  - weekday

unused_fields:  # Features to drop before pipeline
  - dteday
  - casual
  - registered
  - day
  
# Features inside processing pipeline

weekday: weekday  #-- WeekdayImputation
  
day: day #-- WeekdayImputation

dteday: dteday #-- WeekdayImputation

weathersit: weathersit #-- WeathersItImputation

year: year #--Year mapping

month: month #--Month mapping

season: season #-- season mapping

holiday: holiday #--holiday mapping

workingday: workingday #--working day

hr: hr #-- hour mapping

temp: temp #-- temp outlier handling

atemp: atemp #-- atemp outlier handling

hum: hum #--hum outlier handling

windspeed: windspeed #--windspeed outlier handling

format: '%Y-%m-%d'

yearmapping:
  2012: 0
  2011: 1

seasonmapping:
 fall: 0
 winter: 1
 spring: 2
 summer: 3

hourmapping:
  6am: 5
  4am: 6
  11am: 7
  7am: 8
  12pm: 9
  9am: 10
  2am: 11
  4pm: 0
  8am: 12
  1am: 13
  3am: 14
  1pm: 15
  10pm: 16
  7pm: 4
  8pm: 17
  2pm: 18
  5pm: 1
  5am: 19
  3pm: 20
  9pm: 21
  10am: 22
  6pm: 3
  12am: 23
  11pm: 24

holmapping:
  No: 0
  Yes: 1

weekdaymapping:
  Mon: 3
  Wed: 4
  Thu: 5
  Tue: 6
  Sun: 1
  Fri: 2
  Sat: 0

workingdaymapping:
  No: 1
  Yes: 0

weathersitmapping:
  Mist: 2
  Clear: 0
  Light Rain: 1
  Heavy Rain: 3

monthmapping:
  November: 7
  July: 0
  February: 5
  March: 6
  June: 8
  January: 3
  December: 2
  May: 1
  September: 9
  August: 10
  October: 11
  April: 4

  
# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 150
max_depth: 5

